### ISSUE TITLE
🐛[BUG]: EDMPrecondSRV2 incompatible with CorrDiff

### ISSUE THREAD

**Issue by tge25** [NVIDIA/physicsnemo#533]
### Version

0.6.0

### On which installation method(s) does this occur?

Docker, Source

### Describe the issue

Error due to args mismatch between EDMPrecondSRV2 and CorrDiff training

### Minimum reproducible example

```shell
python3 train.py --config-name=config_train_diffusion.yaml
config: 
    arch: edm
```

### Relevant log output

```shell
Traceback (most recent call last): 
  File "/code/modulus/examples/generative/corrdiff/train.py", line 344, in 
main 
    training_loop.training_loop( 
  File 
"/code/modulus/examples/generative/corrdiff/training/training_loop.py", 
line 166, in training_loop   <-------------- 
    net = construct_class_by_name(**merged_args)  # subclass of 
torch.nn.Module 
  File "/code/modulus/modulus/utils/generative/utils.py", line 306, in 
construct_class_by_name 
    return call_func_by_name(*args, func_name=class_name, **kwargs) 
  File "/code/modulus/modulus/utils/generative/utils.py", line 296, in 
call_func_by_name 
    return func_obj(*args, **kwargs) 
  File "/code/modulus/modulus/models/diffusion/preconditioning.py", line 
969, in __init__ <-------------- 
    model = model_class( 
  File "/code/modulus/modulus/models/module.py", line 65, in __new__ 
    bound_args = sig.bind_partial( 
  File "/usr/lib/python3.10/inspect.py", line 3193, in bind_partial 
    return self._bind(args, kwargs, partial=True) 
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind 
    raise TypeError( 
TypeError: got an unexpected keyword argument 'img_channels'
```
```


### Environment details

_No response_

**Comment by CharlelieLrt** [comment]
This has been fixed.
