### ISSUE TITLE
🐛[BUG]: Cannot load model with additional buffers registered

### ISSUE THREAD

**Issue by simonbyrne** [NVIDIA/physicsnemo#586]
### Version

0.6.0

### On which installation method(s) does this occur?

Docker

### Describe the issue

I wanted to include the normalization coefficients in the saved model, so I attached them via
```python
net.register_buffer("norm_coeffs", norm_coeffs)
```

However when I reload the checkpoint via 
```python
net = Module.from_checkpoint(filename)
```
I get the following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/modulus/models/module.py", line 363, in from_checkpoint
    model.load_state_dict(model_dict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for EDMPrecond:
        Unexpected key(s) in state_dict: "norm_coeffs". 
```

**Comment by mnabian** [comment]
@loliverhennigh could you please take a look at this issue?

**Comment by pzharrington** [comment]
Hi @simonbyrne -- I know this has sat around for a long time but thanks for raising it. I am not convinced this behavior is really a bug, as the usage of `.from _checkpoint` is intended to be such that the model is consistently constructable/reproducible based on (serializable) args passed to `__init__` alone. What can be improved here is our documentation of that detail, so I will add some additional description to the docs.

Registering additional parameters/buffers outside of the model constructor is more of a non-standard pattern and in that case we provide the `Module.load` method which requires the model to be constructed (and all buffers/extras registered) before loading a state dict.
