### ISSUE TITLE
Unable to Successfully Install nvidia-modulus

### ISSUE THREAD

**Issue by roy0502** [NVIDIA/physicsnemo#746]
When I execute the command `pip install nvidia-modulus[all]`,Additional information: I ran the above command in JupyterLab. the following error occurs.

```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Collecting nvidia-modulus[all]
  Downloading nvidia_modulus-0.9.0-py3-none-any.whl.metadata (21 kB)
Collecting torch>=2.0.0 (from nvidia-modulus[all])
  Downloading torch-2.5.1-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting numpy<1.25,>=1.22.4 (from nvidia-modulus[all])
  Downloading numpy-1.24.4.tar.gz (10.9 MB)
     ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/10.9 MB 8.3 MB/s eta 0:00:02
     ----- ---------------------------------- 1.6/10.9 MB 10.5 MB/s eta 0:00:01
     ------------------ --------------------- 5.0/10.9 MB 9.7 MB/s eta 0:00:01
     --------------------------- ------------ 7.6/10.9 MB 10.9 MB/s eta 0:00:01
     ------------------------------------- - 10.5/10.9 MB 11.5 MB/s eta 0:00:01
     --------------------------------------- 10.9/10.9 MB 11.5 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [33 lines of output]
  Traceback (most recent call last):
    File "[C:\Users\ksuch\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353](file:///C:/Users/ksuch/anaconda3/Lib/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py#line=352), in <module>
      main()
    File "[C:\Users\ksuch\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335](file:///C:/Users/ksuch/anaconda3/Lib/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py#line=334), in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "[C:\Users\ksuch\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112](file:///C:/Users/ksuch/anaconda3/Lib/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py#line=111), in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "[C:\Users\ksuch\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77](file:///C:/Users/ksuch/anaconda3/Lib/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py#line=76), in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "[C:\Users\ksuch\anaconda3\Lib\importlib\__init__.py", line 90](file:///C:/Users/ksuch/anaconda3/Lib/importlib/__init__.py#line=89), in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "[C:\Users\ksuch\AppData\Local\Temp\pip-build-env-sr9nvs4v\overlay\Lib\site-packages\setuptools\__init__.py", line 16](file:///C:/Users/ksuch/AppData/Local/Temp/pip-build-env-sr9nvs4v/overlay/Lib/site-packages/setuptools/__init__.py#line=15), in <module>
      import setuptools.version
    File "[C:\Users\ksuch\AppData\Local\Temp\pip-build-env-sr9nvs4v\overlay\Lib\site-packages\setuptools\version.py", line 1](file:///C:/Users/ksuch/AppData/Local/Temp/pip-build-env-sr9nvs4v/overlay/Lib/site-packages/setuptools/version.py#line=0), in <module>
      import pkg_resources
    File "[C:\Users\ksuch\AppData\Local\Temp\pip-build-env-sr9nvs4v\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172](file:///C:/Users/ksuch/AppData/Local/Temp/pip-build-env-sr9nvs4v/overlay/Lib/site-packages/pkg_resources/__init__.py#line=2171), in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by saydemr** [comment]
I think the problem is related to python version, not nvidia-modulus. Could you check this link: https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

**Comment by roy0502** [comment]
I have already tried adjusting the Python version and avoiding issues related to NumPy, but now a new problem has appeared as shown in the image

![Image](https://github.com/user-attachments/assets/490fb870-16e7-412b-a99e-072c003ecf7a)

**Comment by saydemr** [comment]
No, you are trying with the same version. You can see the line that downloads numpy has a upper bound. Please, refer to the [readme](https://github.com/NVIDIA/modulus?tab=readme-ov-file#package) about installing it from source package or use the command I just shared above (more convenient for jupyter notebooks).

**Comment by saydemr** [comment]
Sorry for misunderstanding. The solution I have provided should work for python `3.12`. I did not try it with python `3.11`.

I think the current problem you are facing with is related to [this](https://github.com/NVIDIA/modulus/issues/723#issuecomment-2494156280). Could you try this then: `pip install --extra-index-url https://pypi.nvidia.com nvidia-modulus`

If this also does not work, I would suggest upgrading to python `3.12` and using `pip install git+https://github.com/NVIDIA/modulus` as before, of course, if you do not have other restrictions about python version.

**Comment by roy0502** [comment]
following the instruction try python 3.12 without numpy 

![Image](https://github.com/user-attachments/assets/e0bf7d04-ef3d-49fe-82e8-2c6fe5c4d359)

**Comment by saydemr** [comment]
Could you try the following then: `pip install --extra-index-url https://pypi.nvidia.com nvidia-modulus`

**Comment by Alrnas** [comment]
Same issue here any solution other than what stated above?

**Comment by abokov-nv** [comment]
Hi @roy0502 , @Alrnas 

Could you please verify if this issue still occurs with PhysicsNeMo latest release? 
Here are the installation instructions: https://docs.nvidia.com/deeplearning/physicsnemo/getting-started/index.html#physicsnemo-with-pip-install
If you're still experiencing the issue, please let us know and share the environment details/scenario. 
Otherwise, we can close this ticket.

Thanks for your help!

**Comment by Alrnas** [comment]
Tried to install this on Colab still has issues, why do we need to downgrade the notebook each time we want to install Modulus? 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.23.0 requires gcsfs!=2025.5.0,>=2023.3.0, which is not installed.
jupyter-kernel-gateway 2.5.2 requires notebook<7.0,>=5.7.6, but you have notebook 7.4.7 which is incompatible.
